kind: pipeline
name: test
type: docker

steps:
  - name: test
    image: maven:3-jdk-8
    commands:
      - mvn test -B

trigger:
  event:
    - push
---
kind: pipeline
name: publish
type: docker

steps:
  - name: build
    image: maven:3-jdk-8
    commands:
      - mvn verify -DskipTests
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: target/waypoints2*
      checksum:
        - md5
        - sha256

depends_on:
  - test

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    - master