kind: pipeline
name: test
type: docker

steps:
  - name: test
    image: maven:3-jdk-8
    commands:
      - mvn test -B

trigger:
  event:
    - push
  branch:
    exclude:
      - master
---
kind: pipeline
name: publish
type: docker

steps:
  - name: test
    image: maven:3-jdk-8
    commands:
      - mvn test -B
  - name: build
    image: maven:3-jdk-8
    commands:
      - mvn verify -B -DskipTests -Pprod
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: target/waypoints2*
      checksum:
        - md5
        - sha256

trigger:
  event:
    include:
      - tag
    exclude:
      - pull_request