kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: maven:3-jdk-8
    commands:
      - mvn test -B
  - name: build
    image: maven:3-jdk-8
    commands:
      - mvn verify
    when:
      branch:
        - master
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: target/waypoints2*
      checksum:
        - md5
        - sha256
    when:
      branch:
        - master

trigger:
  event:
    - push