name: Waypoints
author: Md5Lukas
main: de.md5lukas.wp.Main
version: 1.4
description: A simple plugin to create and manage waypoints
api-version: 1.13
depend: [SmartInvs]

commands:
  waypoints:
    aliases: [wp, waypoint]
    description: The main command to use this plugin