general:
  # Set the language for the plugin here
  language: en
  uuidCache:
    # Max size of the internal UUID-Cache
    maxSize: 100
    # Set time in hours after saved UUIDs will be removed from the cache
    expireAfter: 24

  customIconFilter:
    type: blacklist
    materials:
      - AIR
      - BARRIER
      - BEDROCK

  waypoints:
    limit: 200

    allowDuplicateNames:
      private: true
      public: false
      permission: false

  folders:
    limit: 20

    allowDuplicateNames:
      private: true
      public: false
      permission: false

  teleport:
    cooldown: 5m
    standStillTime: 3s

    # Available types are: disabled, free, xp (levels), vault (your economy plugins currency)
    # You can provide a formula to calculate the price. The variable n is how often a player teleported
    # When using the payment method xp the returned value is rounded to the closest full value
    private:
      type: xp
      maxCost: 10
      formula: 1 + n

    public:
      type: xp
      maxCost: 8
      formula: 1 + n

    permission:
      type: free
      maxCost: 3
      formula: n

pointers:
  # Automatically deselects the waypoint when the player gets into the defined radius. Set to zero to disable
  disableWhenReachedRadius: 5

  actionBar:
    enabled: true
    interval: 20
    indicatorColor: "&4&l"
    normalColor: "&7&l"
    section: "⬛"
    arrow:
      left: "<-"
      right: "->"
    amountOfSections: 35
    range: 70

  beacon:
    enabled: true

    interval: 30
    minDistance: 50
    maxDistance: auto
    baseBlock: IRON_BLOCK
    defaultColor:
      private: CLEAR
      public: GREEN
      permission: PURPLE
      death: RED

  blinkingBlock:
    enabled: true

    # The interval in game ticks when the block should be changed
    interval: 20
    # The minimum and maximum distance for the blinking block to be visible
    # Keep in mind that if you set the min distance to low it could be possible for the player to stand on the client-side block and get kicked for flying
    minDistance: 10
    maxDistance: 50
    # The blocks that will be cycled through
    blockSequence:
      - GLASS
      - GLOWSTONE

  compass:
    enabled: true

  particle:
    enabled: true
    interval: 30
    heightOffset: 0
    showVerticalDirection: false
    amount: 10
    length: 1
    particle: FLAME

inventory:
  general:
    previous: ARROW
    next: ARROW
    back: BARRIER

  background:
    private: GREEN_STAINED_GLASS_PANE
    death: RED_STAINED_GLASS_PANE
    public: BLUE_STAINED_GLASS_PANE
    permission: YELLOW_STAINED_GLASS_PAME

  overview:
    cycleSort: HOPPER
    toggleGlobals:
      visible: CHEST
      hidden: CHEST
    deselect: MILK_BUCKET
    setWaypoint: TORCH
    createFolder: WRITABLE_BOOK

  listing:
    private: BOOK
    permission: BOOK

  waypoint:
    icon:
      private: SKELETON_SKULL
      death: BEACON
      public: BEACON
      permission: BEACON

    select: REDSTONE
    delete: LAVA_BUCKET
    rename: NAME_TAG
    moveToFolder: CHEST_MINECART
    teleport: ENDER_PEARL
    selectBeaconColor: LIME_STAINED_GLASS
    getUuid: PAPER

  folder:
    icon:
      private: BOOK
      public: ENCHANTED_BOOK
      permission: ENCHANTED_BOOK

    delete: LAVA_BUCKET
    rename: NAME_TAG

  selectFolder:
    noFolder: MINECART

  confirm:
    background: LIGHT_GRAY_STAINED_GLASS_PANE

  delete:
    waypoint:
      question: OAK_SIGN
      confirm: LAVA_BUCKET
      cancel: WATER_BUCKET
    folder:
      question: OAK_SIGN
      confirm: LAVA_BUCKET
      cancel: WATER_BUCKET
