name: Waypoints
author: Md5Lukas
main: de.md5lukas.waypoints.WaypointsPlugin
version: ${version}

api-version: 1.14

commands:
  waypoints:
    aliases:
      - wp
  waypointsscript:
    permission: waypoints.command.scripting
    aliases:
      - wps

permissions:
  waypoints.*:
    default: op
    children:
      - waypoints.command.scripting
      - waypoints.command.use
      - waypoints.command.other
      - waypoints.modify.private
      - waypoints.modify.public
      - waypoints.modify.permission

  waypoints.command.scripting:
    default: op

  waypoints.command.use:
    default: true
  waypoints.command.other:
    default: op

  waypoints.modify.private:
    default: true
    children:
      - waypoints.modify.waypoint.private
      - waypoints.modify.folder.private
  waypoints.modify.waypoint.private:
    default: true
  waypoints.modify.folder.private:
    default: true

  waypoints.modify.public:
    default: op
    children:
      - waypoints.modify.waypoint.public
      - waypoints.modify.folder.public
  waypoints.modify.waypoint.public:
    default: op
  waypoints.modify.folder.public:
    default: op

  waypoints.modify.permission:
    default: op
    children:
      - waypoints.modify.waypoint.permission
      - waypoints.modify.folder.permission
  waypoints.modify.waypoint.permission:
    default: op
  waypoints.modify.folder.permission:
    default: op