name: Waypoints
author: Md5Lukas
main: de.md5lukas.waypoints.WaypointsPlugin
version: ${version}

website: https://github.com/Sytm/waypoints

api-version: ${apiVersion}

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}

softdepend:
  - Vault
  - dynmap
  - ProtocolLib

commands:
  waypoints:
    aliases:
      - wp
  waypointsscript:
    permission: waypoints.command.scripting
    aliases:
      - wps

permissions:
  waypoints.*:
    default: op
    children:
      - waypoints.command.scripting
      - waypoints.command.use
      - waypoints.command.other
      - waypoints.command.statistics
      - waypoints.command.import
      - waypoints.unlimited
      - waypoints.modify.private
      - waypoints.modify.public
      - waypoints.modify.permission
      - waypoints.teleport.private
      - waypoints.teleport.public
      - waypoints.teleport.permission
      - waypoints.tracking.enabled
      - waypoints.tracking.trackAll

  waypoints.command.scripting: { }
  waypoints.command.use:
    default: true
  waypoints.command.other: { }
  waypoints.command.statistics: { }
  waypoints.command.import: { }

  waypoints.unlimited: { }
  waypoints.temporaryWaypoint:
    default: true

  waypoints.modify.private:
    default: true
  waypoints.modify.public: { }
  waypoints.modify.permission: { }

  waypoints.teleport.private: { }
  waypoints.teleport.public: { }
  waypoints.teleport.permission: { }

  waypoints.tracking.enabled:
    default: true
  waypoints.tracking.trackAll: { }
