name: Waypoints
author: Md5Lukas
main: de.md5lukas.waypoints.WaypointsPlugin
version: ${version}

website: https://github.com/Sytm/waypoints

api-version: 1.16

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}

softdepend:
  - Vault

commands:
  waypoints:
    aliases:
      - wp
  waypointsscript:
    permission: waypoints.command.scripting
    aliases:
      - wps

permissions:
  waypoints.*:
    default: op
    children:
      - waypoints.command.scripting
      - waypoints.command.use
      - waypoints.command.other
      - waypoints.command.statistics
      - waypoints.command.import
      - waypoints.unlimited
      - waypoints.modify.private
      - waypoints.modify.public
      - waypoints.modify.permission
      - waypoints.teleport.*

  waypoints.command.*:
    default: op
    children:
      - waypoints.command.scripting
      - waypoints.command.use
      - waypoints.command.other
      - waypoints.command.import

  waypoints.command.scripting: { }
  waypoints.command.use:
    default: true
  waypoints.command.other: { }
  waypoints.command.statistics: { }
  waypoints.command.import: { }

  waypoints.unlimited:
    default: op

  waypoints.modify.private:
    default: true
  waypoints.modify.public:
    default: op
  waypoints.modify.permission:
    default: op

  waypoints.teleport.*:
    default: op
    children:
      - waypoints.teleport.private
      - waypoints.teleport.public
      - waypoints.teleport.permission
  waypoints.teleport.private: { }
  waypoints.teleport.public: { }
  waypoints.teleport.permission: { }
